persistence:
  enabled: true
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "standard"
  resources:
    requests:
      storage: 4Gi
replicas: 3
antiAffinity: "soft"
esJavaOpts: "-Xmx512m -Xms512m"
resources:
  requests:
    cpu: "1000m"
    memory: "1G"
  limits:
    cpu: "1000m"
    memory: "1G"
lifecycle:
  postStart:
    exec:
      command:
        - bash
        - -c
        - |
          #!/bin/bash
          # Add a template to adjust number of shards/replicas
          while [[ "$(curl -s -o /dev/null -w '%{http_code}\n' -L http://localhost:9200)" != "200" ]]; do sleep 1; done
          curl -X PUT "http://localhost:9200/_index_template/logstash?pretty" -H 'Content-Type: application/json' -d'{ "index_patterns": ["logstash-*"], "template": { "settings": { "index": { "lifecycle": { "name": "7-days-default", "rollover_alias": "logstash" }, "number_of_replicas": "2" } }, "mappings": { "dynamic": "true", "properties": {} }, "aliases": { "logstash": {} } }, "priority": 500, "data_stream": { }, "composed_of": ["data-streams-mappings"], "version": 1.0, "_meta": { "description": "logstash from fluent-bit", "managed": true } }'
