lifecycle:
  postStart:
    exec:
      command:
        - bash
        - -c
        - |
          #!/bin/bash
          # Import a dashboard
          while [[ "$(curl -s -o /dev/null -w '%{http_code}\n' -L http://localhost:5601)" != "200" ]]; do sleep 1; done
          curl -X POST "http://localhost:5601/api/index_patterns/index_pattern" -H 'kbn-xsrf: true' -H 'Content-Type: application/json' -d'{"index_pattern":{"title":"logstash-*","timeFieldName":"@timestamp"}}'
